"""Fallback summarizer: turn a folder of raw logs into pattern summaries.

SEAM NOTICE. The telemetry pipeline is out of scope for this PoC, but pattern summaries
are load-bearing -- `loader.build_slice_catalog` turns their `log_pointers` into slices,
and slices are the only thing the commander can dispatch a grunt against. Without
summaries, a folder of logs is invisible to the entire system.

So this module stands in for the pipeline: it chunks each log into windows and computes
statistics that are *real but generic*. What it cannot do is the part that makes the
pipeline valuable -- cross-host prevalence, historical baselines, genuine first-seen,
interval regularity scoring against a population. It says so, in the summary text the
commander reads.

That honesty is not politeness. The first real run showed the commander citing summary
statistics as evidence in the brief; if it is handed weak statistics wearing a
pipeline-grade label, it will launder them into conclusions. A hand-written `patterns/`
directory in the case folder overrides everything here.
"""

from __future__ import annotations

import re
from collections import Counter
from pathlib import Path

from soc_poc.schemas.pattern_summary import LogPointer, PatternSummary

# Total slices across all logs. The commander can only read
# max_tasks_per_iteration x max_iterations of them (12 by default), so going much wider
# mostly produces a catalog it has to skim. analyze.py warns when the two disagree.
DEFAULT_MAX_SLICES = 24
DEFAULT_WINDOW_LINES = 50
MIN_WINDOW_LINES = 20

_ISO_TS = re.compile(r"\b\d{4}-\d{2}-\d{2}[T ]\d{2}:\d{2}:\d{2}(?:\.\d+)?Z?\b")
_SYSLOG_TS = re.compile(r"\b[A-Z][a-z]{2}\s+\d{1,2}\s+\d{2}:\d{2}:\d{2}\b")

# Normalisers used to collapse lines into templates. Order matters: addresses before
# bare numbers, or the digits inside an IP get eaten first.
_TEMPLATE_RULES: tuple[tuple[re.Pattern[str], str], ...] = (
    (_ISO_TS, "<TS>"),
    (_SYSLOG_TS, "<TS>"),
    (re.compile(r"\b(?:\d{1,3}\.){3}\d{1,3}\b"), "<IP>"),
    (re.compile(r"\b[0-9a-fA-F]{2}(?::[0-9a-fA-F]{2}){5}\b"), "<MAC>"),
    (re.compile(r"\b0x[0-9a-fA-F]+\b"), "<HEX>"),
    (re.compile(r"\b[0-9a-fA-F]{16,}\b"), "<HASH>"),
    (re.compile(r"\d+"), "<N>"),
)


def _templatize(line: str) -> str:
    for pattern, replacement in _TEMPLATE_RULES:
        line = pattern.sub(replacement, line)
    return line.strip()[:200]


def _timestamps(lines: list[str]) -> list[str]:
    found: list[str] = []
    for line in lines:
        match = _ISO_TS.search(line) or _SYSLOG_TS.search(line)
        if match:
            found.append(match.group(0))
    return found


def _time_range(lines: list[str]) -> str:
    stamps = _timestamps(lines)
    if not stamps:
        return "unknown (no timestamps recognised in this file)"
    # Lexical min/max is correct for ISO-8601 and good enough for syslog within a month.
    return f"{min(stamps)}/{max(stamps)}"


def _window_size(total_lines: int, files: int, max_slices: int) -> int:
    """Pick a window size so the whole corpus fits inside the slice budget."""
    budget = max(1, max_slices)
    # Every file gets at least one window, so the budget available for splitting is
    # what remains after that floor.
    if files >= budget:
        return max(MIN_WINDOW_LINES, total_lines)
    size = DEFAULT_WINDOW_LINES
    while (total_lines + size - 1) // size > budget and size < total_lines:
        size *= 2
    return max(MIN_WINDOW_LINES, size)


def summarize_log(path: Path, window_lines: int) -> PatternSummary:
    lines = path.read_text(encoding="utf-8", errors="replace").splitlines()
    line_count = len(lines)
    templates = Counter(_templatize(line) for line in lines if line.strip())
    top_template, top_count = (templates.most_common(1) or [("", 0)])[0]

    pointers = [
        LogPointer(
            file=path.name,
            start_line=start + 1,
            end_line=min(start + window_lines, line_count),
            why=f"lines {start + 1}-{min(start + window_lines, line_count)} of "
            f"{line_count} (window {index} of "
            f"{(line_count + window_lines - 1) // window_lines})",
        )
        for index, start in enumerate(range(0, max(line_count, 1), window_lines), start=1)
    ]

    return PatternSummary(
        summary_id=f"auto-{path.stem}",
        title=f"Auto-chunked contents of {path.name}",
        source=path.stem,
        host="unknown",
        time_range=_time_range(lines),
        description=(
            f"Generated by the fallback summarizer, NOT by the telemetry pipeline. The "
            f"file was split into windows of {window_lines} lines so its contents can be "
            f"dispatched to workers; no pattern detection was performed. The statistics "
            f"below are counted from this file alone -- there is no cross-host "
            f"prevalence, no historical baseline, and no genuine first-seen. Treat them "
            f"as a description of the data volume, not as evidence, and rely on what the "
            f"workers actually read in the lines."
        ),
        stats={
            "generated_by": "fallback_summarizer",
            "line_count": str(line_count),
            "window_lines": str(window_lines),
            "windows": str(len(pointers)),
            "distinct_line_templates": str(len(templates)),
            "most_common_template": top_template or "(none)",
            "most_common_template_count": str(top_count),
            "timestamped_lines": str(len(_timestamps(lines))),
        },
        log_pointers=pointers,
    )


def summarize_logs(
    logs_dir: Path, *, max_slices: int = DEFAULT_MAX_SLICES
) -> list[PatternSummary]:
    """One summary per log file, windowed to fit the slice budget."""
    paths = sorted(p for p in logs_dir.iterdir() if p.is_file() and not p.name.startswith("."))
    if not paths:
        raise FileNotFoundError(f"no log files found in {logs_dir}")

    total_lines = sum(
        len(p.read_text(encoding="utf-8", errors="replace").splitlines()) for p in paths
    )
    window = _window_size(total_lines, len(paths), max_slices)
    return [summarize_log(path, window) for path in paths]
